name: UpdateCode

on:
  push:
    branches: [main, develop, unstable, stable]

jobs:
  Update_Codes:
    runs-on: [self-hosted]
    steps:
      - name: Start
        run: |
          echo "Start"
          echo "Push Created : To [${{ github.ref_name }}]"
      - name: Pull Codes
        run: |
          cd ~/test_ws/test_action/${{ github.event.repository.name }}
          git checkout ${{ github.ref_name }}
          git pull
